---
- become: yes
  become_method: sudo
  hosts: webservers
  tasks:
          - name: Download tomcat installation script
            get_url:
              url:  https://raw.githubusercontent.com/Jenkinsaks/Ansible-IaS/main/tomcat.sh
              dest: /home/azureuser/tomcat.sh
              mode: 0755

          - name: Download postgres installation script
            get_url:
              url: https://raw.githubusercontent.com/Jenkinsaks/Ansible-IaS/main/Postgresql-Install-1.sh
              dest: /home/azureuser/Postgresql-Install1.sh
              mode: 0755

          - name: Run tomcat script
             shell: /home/azureuser/tomcat.sh

          - name: Run postgress script
            shell: /home/azureuser/Postgresql-Install1.sh
