---
- become: yes
  become_method: sudo
  hosts: localhost
  tasks:
          - name: Download jenkins installation script
            get_url:
              url:  https://raw.githubusercontent.com/Jenkinsaks/Ansible-IaS/main/jenkinsubuntu.sh
              dest: /home/azureuser/jenkinsubuntu.sh
              mode: 0755

          - name: Download docker installation script
            get_url:
              url: https://raw.githubusercontent.com/Jenkinsaks/Ansible-IaS/main/dockerubuntu.sh
              dest: /home/azureuser/dockerubuntu.sh
              mode: 0755

          - name: Run jenkins script
            shell: /home/azureuser/jenkinsubuntu.sh

          - name: Run docker script
            shell: /home/azureuser/dockerubuntu.sh
            
          - name: Download Sonar installation script
            get_url:
              url: https://raw.githubusercontent.com/Jenkinsaks/Ansible-IaS/main/sonar.sh
              dest: /home/azureuser/sonar.sh
              mode: 0755

          - name: Run jenkins script
            shell: /home/azureuser/sonar.sh
